- name: Setup Filebeat
  hosts: all
  become: yes

  tasks:
    - name: Ensure required dependencies are present.
      apt:
        name:
          - apt-transport-https
          - gnupg2
        state: present

    - name: Add Elasticsearch apt key with web proxy.
      apt_key:
        url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
        id: 46095ACC8548582C1A2699A9D27D666CD88E42B4
        state: present
      environment:
       http_proxy: "{{ WEB_PROXY }}"
       https_proxy: "{{ WEB_PROXY }}"
      when: PROXY_ENABLED

    - name: Add Elasticsearch apt key.
      apt_key:
        url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
        id: 46095ACC8548582C1A2699A9D27D666CD88E42B4
        state: present
      when: PROXY_ENABLED == false

    - name: Add Filebeat repository.
      apt_repository:
        repo: 'deb https://artifacts.elastic.co/packages/{{ FILEBEAT_VERSION }}/apt stable main'
        state: present
        update_cache: true

    - name: Install Filebeat.
      package: name=filebeat state=present

    - name: Copy Filebeat configuration.
      ansible.builtin.template:
        src: files/filebeat.yml.j2
        dest: /etc/filebeat/filebeat.yml
        owner: root
        group: root
        mode: 0644

    - name: Ensure Filebeat is started and enabled at boot.
      service:
        name: filebeat
        state: started
        enabled: true